version: "3"

networks:
  tiki:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
          gateway: 172.20.0.1

services:
  server:
    image: server:v2
    container_name: server
    ports:
      - "8081:8081"
    networks:
      tiki:
        ipv4_address: 172.20.0.2
    depends_on:
      - mysql

  mysql:
    image: mysql:v1
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    networks:
      tiki:
        ipv4_address: 172.20.0.3
